export interface RoadmapStage {
  id: string;
  name: string;
  description: string;
  order: number;
  topics: RoadmapTopic[];
}

export interface RoadmapTopic {
  id: string;
  name: string;
  subtopic: string;
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
  importance: 'critical' | 'high' | 'medium' | 'low';
  estimatedHours: number;
  questionCount: number;
  description: string;
  unlocks: string[];
  requires: string[];
  companyFrequency: string[];
}

export const ROADMAP_STAGES: RoadmapStage[] = [
  {
    id: 'foundation-math',
    name: 'Stage 1: Foundation Math',
    description: 'Number sense and divisibility — the base for everything else in quant. Master these first.',
    order: 1,
    topics: [
      {
        id: 'number_system',
        name: 'Number System',
        subtopic: 'number_system',
        category: 'quant',
        difficulty: 'easy',
        importance: 'critical',
        estimatedHours: 4,
        questionCount: 15,
        description: 'Integers, fractions, decimals, squares, cubes, divisibility rules. Unlocks HCF/LCM and percentages.',
        unlocks: ['hcf_lcm', 'divisibility', 'percentages'],
        requires: [],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture'],
      },
      {
        id: 'hcf_lcm',
        name: 'HCF & LCM',
        subtopic: 'hcf_lcm',
        category: 'quant',
        difficulty: 'easy',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Highest Common Factor, Least Common Multiple, Product = HCF × LCM. Used in Time-Work and Pipes-Cisterns.',
        unlocks: ['time_work', 'pipes_cisterns'],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro'],
      },
      {
        id: 'divisibility',
        name: 'Divisibility & Simplification',
        subtopic: 'divisibility',
        category: 'quant',
        difficulty: 'easy',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 10,
        description: 'BODMAS, unit digit, remainder theorem, simplification shortcuts. Builds calculation speed.',
        unlocks: [],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'HCL'],
      },
    ],
  },
  {
    id: 'core-arithmetic',
    name: 'Stage 2: Core Arithmetic',
    description: 'The three pillars of quant. ~80% of placement quant questions trace back to these.',
    order: 2,
    topics: [
      {
        id: 'percentages',
        name: 'Percentages',
        subtopic: 'percentages',
        category: 'quant',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 5,
        questionCount: 20,
        description: 'Successive percentage change, comparison, percentage to fraction conversion. Unlocks Profit/Loss, SI, CI, Mixtures.',
        unlocks: ['profit_loss', 'simple_interest', 'compound_interest', 'mixtures_alligations'],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Capgemini'],
      },
      {
        id: 'ratios_proportions',
        name: 'Ratios & Proportions',
        subtopic: 'ratios_proportions',
        category: 'quant',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 4,
        questionCount: 15,
        description: 'Direct/indirect proportion, componendo-dividendo, chain rule. Unlocks Ages, Partnership, Mixtures, Alligations, TSD.',
        unlocks: ['ages', 'partnership', 'mixtures_alligations', 'time_speed_distance'],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture'],
      },
      {
        id: 'averages',
        name: 'Averages',
        subtopic: 'averages',
        category: 'quant',
        difficulty: 'easy',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Weighted average, average of first n numbers, replacement problems. Used in Ages and DI.',
        unlocks: ['ages', 'data_interpretation'],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Wipro', 'HCL'],
      },
    ],
  },
  {
    id: 'applied-quant',
    name: 'Stage 3: Applied Quant',
    description: 'Business math. These are direct applications of Stage 2 concepts.',
    order: 3,
    topics: [
      {
        id: 'profit_loss',
        name: 'Profit & Loss',
        subtopic: 'profit_loss',
        category: 'quant',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 4,
        questionCount: 18,
        description: 'Discount, marked price, successive discounts, faulty weights. Heavy in every company exam.',
        unlocks: [],
        requires: ['percentages'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Deloitte'],
      },
      {
        id: 'simple_interest',
        name: 'Simple Interest',
        subtopic: 'simple_interest',
        category: 'quant',
        difficulty: 'easy',
        importance: 'high',
        estimatedHours: 2,
        questionCount: 10,
        description: 'SI = P×R×T/100. Amount calculations. Foundation for Compound Interest.',
        unlocks: ['compound_interest'],
        requires: ['percentages'],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'compound_interest',
        name: 'Compound Interest',
        subtopic: 'compound_interest',
        category: 'quant',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 10,
        description: 'Half-yearly, quarterly compounding, difference between SI and CI. Less frequent but scoring.',
        unlocks: [],
        requires: ['percentages', 'simple_interest'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'ages',
        name: 'Problems on Ages',
        subtopic: 'ages',
        category: 'quant',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Present/past/future age ratios. Age difference is constant over time.',
        unlocks: [],
        requires: ['ratios_proportions', 'averages'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro'],
      },
      {
        id: 'partnership',
        name: 'Partnership',
        subtopic: 'partnership',
        category: 'quant',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 10,
        description: 'Profit sharing based on investment × time. Direct application of ratios.',
        unlocks: [],
        requires: ['ratios_proportions'],
        companyFrequency: ['TCS', 'Accenture'],
      },
    ],
  },
  {
    id: 'rate-problems',
    name: 'Stage 4: Rate Problems',
    description: 'The most feared and most important section. These separate the good from the great.',
    order: 4,
    topics: [
      {
        id: 'time_work',
        name: 'Time & Work',
        subtopic: 'time_work',
        category: 'quant',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 5,
        questionCount: 16,
        description: 'Combined rates, efficiency, alternate days, partial work. Core concept: rate = 1/time.',
        unlocks: ['pipes_cisterns'],
        requires: ['hcf_lcm'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Capgemini'],
      },
      {
        id: 'pipes_cisterns',
        name: 'Pipes & Cisterns',
        subtopic: 'pipes_cisterns',
        category: 'quant',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 10,
        description: 'Inlet/outlet problems. Net rate = 1/inlet - 1/outlet. Extension of Time-Work.',
        unlocks: [],
        requires: ['time_work'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro'],
      },
      {
        id: 'time_speed_distance',
        name: 'Time, Speed & Distance',
        subtopic: 'time_speed_distance',
        category: 'quant',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 6,
        questionCount: 18,
        description: 'Trains, platforms, average speed, relative speed. Most repeated pattern in all exams.',
        unlocks: ['boats_streams'],
        requires: ['ratios_proportions'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Deloitte', 'IBM'],
      },
      {
        id: 'boats_streams',
        name: 'Boats & Streams',
        subtopic: 'boats_streams',
        category: 'quant',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 10,
        description: 'Upstream, downstream, still water speed. Extension of TSD.',
        unlocks: [],
        requires: ['time_speed_distance'],
        companyFrequency: ['TCS', 'Wipro'],
      },
    ],
  },
  {
    id: 'advanced-quant',
    name: 'Stage 5: Advanced Quant',
    description: 'Score boosters. Fewer questions but high differentiation.',
    order: 5,
    topics: [
      {
        id: 'mixtures_alligations',
        name: 'Mixtures & Alligations',
        subtopic: 'mixtures_alligations',
        category: 'quant',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 10,
        description: 'Replacing mixture, combining mixtures, alligation rule. Uses ratios + percentages.',
        unlocks: [],
        requires: ['percentages', 'ratios_proportions'],
        companyFrequency: ['TCS', 'Accenture', 'Capgemini'],
      },
      {
        id: 'probability',
        name: 'Probability',
        subtopic: 'probability',
        category: 'quant',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 4,
        questionCount: 15,
        description: 'Coins, dice, cards, independent/dependent events. Concept-heavy, formula-light.',
        unlocks: [],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'permutations_combinations',
        name: 'Permutations & Combinations',
        subtopic: 'permutations_combinations',
        category: 'quant',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 5,
        questionCount: 14,
        description: 'Arrangements, selections, circular permutations, derangements. Toughest quant topic.',
        unlocks: [],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'mensuration',
        name: 'Mensuration',
        subtopic: 'mensuration',
        category: 'quant',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 4,
        questionCount: 15,
        description: 'Area, volume, surface area of 2D/3D shapes. Formula memorization + application.',
        unlocks: [],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'clocks',
        name: 'Clocks',
        subtopic: 'clocks',
        category: 'quant',
        difficulty: 'easy',
        importance: 'low',
        estimatedHours: 2,
        questionCount: 10,
        description: 'Angle between hands, coinciding hands, mirror time. Formula-based.',
        unlocks: [],
        requires: ['number_system'],
        companyFrequency: ['TCS'],
      },
      {
        id: 'calendars',
        name: 'Calendars',
        subtopic: 'calendars',
        category: 'quant',
        difficulty: 'easy',
        importance: 'low',
        estimatedHours: 2,
        questionCount: 10,
        description: 'Odd days, leap years, day of the week. Odd days method.',
        unlocks: [],
        requires: ['number_system'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'data_interpretation',
        name: 'Data Interpretation',
        subtopic: 'data_interpretation',
        category: 'quant',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 6,
        questionCount: 197,
        description: 'Bar charts (90), pie charts (57), line charts (50). Requires percentages, ratios, averages.',
        unlocks: [],
        requires: ['percentages', 'ratios_proportions', 'averages'],
        companyFrequency: ['TCS', 'Accenture', 'Capgemini'],
      },
    ],
  },
  {
    id: 'core-reasoning',
    name: 'Stage 6: Core Reasoning',
    description: 'Pattern recognition and basic logic. Entry point into reasoning section.',
    order: 6,
    topics: [
      {
        id: 'series',
        name: 'Number & Letter Series',
        subtopic: 'series',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 4,
        questionCount: 20,
        description: 'Arithmetic, geometric, alternate, cube/square patterns. Most common reasoning question.',
        unlocks: ['coding_decoding'],
        requires: [],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture'],
      },
      {
        id: 'coding_decoding',
        name: 'Coding-Decoding',
        subtopic: 'coding_decoding',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Letter shifting, substitution, pattern-based codes. Builds pattern recognition.',
        unlocks: [],
        requires: ['series'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro'],
      },
      {
        id: 'blood_relations',
        name: 'Blood Relations',
        subtopic: 'blood_relations',
        category: 'reasoning',
        difficulty: 'easy',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Family tree problems. Draw diagram first. Paternal vs maternal sides.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Wipro', 'Accenture'],
      },
      {
        id: 'direction_sense',
        name: 'Direction Sense',
        subtopic: 'direction_sense',
        category: 'reasoning',
        difficulty: 'easy',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 15,
        description: 'Shadow-based, turning-based displacement. Track net movement on axes.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'analogies',
        name: 'Analogies',
        subtopic: 'analogies',
        category: 'reasoning',
        difficulty: 'easy',
        importance: 'low',
        estimatedHours: 2,
        questionCount: 15,
        description: 'Word/number relationship matching. Pattern recognition skill.',
        unlocks: [],
        requires: [],
        companyFrequency: ['Infosys', 'Wipro'],
      },
    ],
  },
  {
    id: 'advanced-reasoning',
    name: 'Stage 7: Advanced Reasoning',
    description: 'Complex arrangement and logical deduction. Time-consuming but high marks.',
    order: 7,
    topics: [
      {
        id: 'seating_arrangement',
        name: 'Seating Arrangement',
        subtopic: 'seating_arrangement',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'critical',
        estimatedHours: 5,
        questionCount: 44,
        description: 'Linear, circular, rectangular seating. Direction facing matters. Most time-consuming.',
        unlocks: ['puzzles'],
        requires: ['direction_sense', 'blood_relations'],
        companyFrequency: ['TCS', 'Accenture', 'Capgemini'],
      },
      {
        id: 'puzzles',
        name: 'Puzzles',
        subtopic: 'puzzles',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 4,
        questionCount: 15,
        description: 'Scheduling, floor-based, order-ranking puzzles. Combine multiple constraints.',
        unlocks: [],
        requires: ['seating_arrangement'],
        companyFrequency: ['TCS', 'Infosys', 'Accenture'],
      },
      {
        id: 'syllogisms',
        name: 'Syllogisms',
        subtopic: 'syllogisms',
        category: 'reasoning',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 14,
        description: 'Venn diagram logic. Valid/invalid conclusions. All/Some/No statements.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'statements_assumptions',
        name: 'Statements & Assumptions',
        subtopic: 'statements_assumptions',
        category: 'reasoning',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 10,
        description: 'Implicit assumptions, conclusions, arguments. Verbal logic.',
        unlocks: ['logical_deductions'],
        requires: [],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'logical_deductions',
        name: 'Logical Deductions',
        subtopic: 'logical_deductions',
        category: 'reasoning',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 10,
        description: 'Propositional logic, truth tables, inference rules. Advanced reasoning.',
        unlocks: [],
        requires: ['statements_assumptions'],
        companyFrequency: ['TCS'],
      },
    ],
  },
  {
    id: 'visual-reasoning',
    name: 'Stage 8: Visual Reasoning',
    description: 'Non-verbal pattern recognition. Figures, images, spatial logic. Asked by TCS, Wipro, Infosys, Cognizant.',
    order: 8,
    topics: [
      {
        id: 'mirror_images',
        name: 'Mirror Images',
        subtopic: 'mirror_images',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 20,
        description: 'Identify mirror reflection of given figures. Left becomes right. Letter/number combinations.',
        unlocks: ['water_images'],
        requires: [],
        companyFrequency: ['TCS', 'Wipro', 'Infosys'],
      },
      {
        id: 'water_images',
        name: 'Water Images',
        subtopic: 'water_images',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'high',
        estimatedHours: 2,
        questionCount: 20,
        description: 'Identify water reflection of figures. Top becomes bottom. Mirror image along horizontal axis.',
        unlocks: [],
        requires: ['mirror_images'],
        companyFrequency: ['TCS', 'Wipro', 'Infosys'],
      },
      {
        id: 'embedded_images',
        name: 'Embedded Images',
        subtopic: 'embedded_images',
        category: 'reasoning',
        difficulty: 'easy',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 20,
        description: 'Find the hidden figure within a complex image. Pattern recognition and visual scanning.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'pattern_completion',
        name: 'Pattern Completion',
        subtopic: 'pattern_completion',
        category: 'reasoning',
        difficulty: 'easy',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 20,
        description: 'Complete the missing piece of a visual pattern. Symmetry, rotation, progression rules.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Wipro', 'Infosys', 'Accenture'],
      },
      {
        id: 'paper_folding',
        name: 'Paper Folding',
        subtopic: 'paper_folding',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 20,
        description: 'Predict the pattern when paper is folded and punched. Visualize layers and holes.',
        unlocks: ['paper_cutting'],
        requires: [],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'paper_cutting',
        name: 'Paper Cutting',
        subtopic: 'paper_cutting',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 19,
        description: 'Determine the unfolded pattern after paper is cut. Extension of paper folding concepts.',
        unlocks: [],
        requires: ['paper_folding'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'cubes_and_dices',
        name: 'Cubes and Dices',
        subtopic: 'cubes_and_dices',
        category: 'reasoning',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 4,
        questionCount: 18,
        description: 'Opposite faces, unfolded cube patterns, dice position problems. Spatial reasoning.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Infosys', 'Wipro'],
      },
      {
        id: 'figure_matrix',
        name: 'Figure Matrix',
        subtopic: 'figure_matrix',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 20,
        description: 'Complete the 3x3 or 4x4 figure matrix. Row/column transformation patterns.',
        unlocks: [],
        requires: ['pattern_completion'],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'classification',
        name: 'Classification',
        subtopic: 'classification',
        category: 'reasoning',
        difficulty: 'easy',
        importance: 'low',
        estimatedHours: 2,
        questionCount: 19,
        description: 'Identify the odd figure out from a group. Spot the dissimilar pattern.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'visual_analogy',
        name: 'Visual Analogy',
        subtopic: 'visual_analogy',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 16,
        description: 'Figure A is to B as C is to ?. Apply the same transformation rule.',
        unlocks: [],
        requires: ['pattern_completion'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'dot_situation',
        name: 'Dot Situation',
        subtopic: 'dot_situation',
        category: 'reasoning',
        difficulty: 'hard',
        importance: 'low',
        estimatedHours: 3,
        questionCount: 20,
        description: 'Identify which figure contains the same dot configuration. Complex spatial matching.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS'],
      },
      {
        id: 'rule_detection',
        name: 'Rule Detection',
        subtopic: 'rule_detection',
        category: 'reasoning',
        difficulty: 'medium',
        importance: 'low',
        estimatedHours: 2,
        questionCount: 11,
        description: 'Find the rule that applies to all given figures. Abstract pattern extraction.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Infosys'],
      },
    ],
  },
  {
    id: 'verbal-foundation',
    name: 'Stage 10: Verbal Foundation',
    description: 'Grammar rules and vocabulary. Builds the base for all verbal questions.',
    order: 10,
    topics: [
      {
        id: 'grammar',
        name: 'Grammar',
        subtopic: 'grammar',
        category: 'verbal',
        difficulty: 'easy',
        importance: 'critical',
        estimatedHours: 4,
        questionCount: 10,
        description: 'Parts of speech, tenses, voice, narration. Foundation for Error Spotting and Sentence Correction.',
        unlocks: ['error_spotting', 'sentence_correction'],
        requires: [],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture'],
      },
      {
        id: 'error_spotting',
        name: 'Error Spotting',
        subtopic: 'error_spotting',
        category: 'verbal',
        difficulty: 'easy',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Subject-verb agreement, tenses, prepositions, modifiers. Most common verbal question.',
        unlocks: [],
        requires: ['grammar'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture'],
      },
      {
        id: 'synonyms',
        name: 'Synonyms',
        subtopic: 'synonyms',
        category: 'verbal',
        difficulty: 'easy',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 10,
        description: 'Same-meaning words. Root word memorization helps.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'antonyms',
        name: 'Antonyms',
        subtopic: 'antonyms',
        category: 'verbal',
        difficulty: 'easy',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 10,
        description: 'Opposite-meaning words. Learn prefixes: un-, dis-, mis-, anti-, de-.',
        unlocks: [],
        requires: [],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'one_word_substitution',
        name: 'One Word Substitution',
        subtopic: 'one_word_substitution',
        category: 'verbal',
        difficulty: 'easy',
        importance: 'low',
        estimatedHours: 2,
        questionCount: 15,
        description: 'Single word for a phrase. E.g., "one who eats everything" = omnivore.',
        unlocks: [],
        requires: [],
        companyFrequency: ['Infosys', 'Wipro'],
      },
    ],
  },
  {
    id: 'verbal-advanced',
    name: 'Stage 11: Verbal Advanced',
    description: 'Context-based and comprehension questions. Comes last because they require all prior skills.',
    order: 11,
    topics: [
      {
        id: 'sentence_correction',
        name: 'Sentence Correction',
        subtopic: 'sentence_correction',
        category: 'verbal',
        difficulty: 'hard',
        importance: 'high',
        estimatedHours: 3,
        questionCount: 15,
        description: 'Identify and fix grammatical errors. Application of Stage 8 grammar rules.',
        unlocks: [],
        requires: ['grammar', 'error_spotting'],
        companyFrequency: ['TCS', 'Infosys', 'Accenture'],
      },
      {
        id: 'fill_blanks',
        name: 'Fill in the Blanks',
        subtopic: 'fill_blanks',
        category: 'verbal',
        difficulty: 'easy',
        importance: 'medium',
        estimatedHours: 2,
        questionCount: 5,
        description: 'Cloze tests — fill missing words in context. Grammar + vocabulary combined.',
        unlocks: [],
        requires: ['grammar'],
        companyFrequency: ['TCS', 'Wipro'],
      },
      {
        id: 'para_jumbles',
        name: 'Para Jumbles',
        subtopic: 'para_jumbles',
        category: 'verbal',
        difficulty: 'hard',
        importance: 'medium',
        estimatedHours: 3,
        questionCount: 5,
        description: 'Rearrange scrambled sentences into coherent paragraph. Look for connectors and chronology.',
        unlocks: ['reading_comprehension'],
        requires: ['grammar'],
        companyFrequency: ['TCS', 'Infosys'],
      },
      {
        id: 'reading_comprehension',
        name: 'Reading Comprehension',
        subtopic: 'reading_comprehension',
        category: 'verbal',
        difficulty: 'hard',
        importance: 'critical',
        estimatedHours: 5,
        questionCount: 168,
        description: 'Passage reading with inference, main idea, tone questions. Most marks in verbal.',
        unlocks: [],
        requires: ['grammar', 'para_jumbles'],
        companyFrequency: ['TCS', 'Infosys', 'Wipro', 'Accenture'],
      },
    ],
  },
];

export function getTopicById(id: string): RoadmapTopic | undefined {
  for (const stage of ROADMAP_STAGES) {
    const topic = stage.topics.find((t) => t.id === id);
    if (topic) return topic;
  }
  return undefined;
}

export function getAllTopics(): RoadmapTopic[] {
  return ROADMAP_STAGES.flatMap((s) => s.topics);
}
